version: '3'

volumes:
  mysql-data:

services: 
  web:
    build:
      context: "."
      dockerfile: "Dockerfile.dev"
    ports:
      - '3000:3000'
    volumes:
      - '.:/shift-app'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db
    environment:
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none


  db:
    image: 'mysql:5.7'
    ports:
      - '4306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - mysql-data:/var/lib/mysql